[build]
command="npm run build"
publish="dist"
functions="netlify/functions"
[functions]
node_bundler="esbuild"
included_files=["netlify/functions/**/*"]
 
# Optional KV binding (if plan supports KV). Safe to keep; ignored if unavailable.
[kv_namespaces]
  [[kv_namespaces]]
    binding = "KV"
    id = "portal-kv"
[[redirects]]
from="/api/*"
to="/.netlify/functions/:splat"
status=200

[[redirects]]
from="/auth/callback"
to="/"
status=302
